---
api_resource_map:
  daemon_set: ExtensionsV1beta1Api
  deployment: ExtensionsV1beta1Api
  job: BatchV1Api
base_path: backup
blacklist:
  - metadata:
    - selfLink
    - uid
    - resourceVersion
    - generation
    - creationTimestamp
    - annotations:
      - kubectl.kubernetes.io/last-applied-configuration
      - kubectl.kubernetes.io/next-controller-id
      - kubectl.kubernetes.io/original-replicas
      - kubectl.kubernetes.io/desired-replicas
      - kubectl.kubernetes.io/update-source-id
  - spec:
    - template:
      - metadata:
        - creationTimestamp
  - status
